robotarm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin #robot_robotarm_kinematics/IKFastKinematicsPlugin   OR   kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
